In [2]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
import statsmodels.api as sm

data = pd.read_excel('Bank_Personal_Loan_Modelling.xlsx', sheet_name = 'Data')
data.head()

,ID,Age,Experience,Income,ZIP Code,Family,CCAvg,Education,Mortgage,Personal Loan,Securities Account,CD Account,Online,CreditCard
0,1,25,1,49,91107,4,1.6,1,0,0,1,0,0,0
1,2,45,19,34,90089,3,1.5,1,0,0,1,0,0,0
2,3,39,15,11,94720,1,1.0,1,0,0,0,0,0,0
3,4,35,9,100,94112,1,2.7,2,0,0,0,0,0,0
4,5,35,8,45,91330,4,1.0,2,0,0,0,0,0,1

In [8]:
x = data.drop(columns = 'Personal Loan')
y = data['Personal Loan']
print(x)
print(y)

        ID  Age  Experience  Income  ZIP Code  Family     CCAvg  Education  \
0        1   25           1      49     91107       4  1.600000          1
1        2   45          19      34     90089       3  1.500000          1
2        3   39          15      11     94720       1  1.000000          1
3        4   35           9     100     94112       1  2.700000          2
4        5   35           8      45     91330       4  1.000000          2
5        6   37          13      29     92121       4  0.400000          2
6        7   53          27      72     91711       2  1.500000          2
7        8   50          24      22     93943       1  0.300000          3
8        9   35          10      81     90089       3  0.600000          2
9       10   34           9     180     93023       1  8.900000          3
10      11   65          39     105     94710       4  2.400000          3
11      12   29           5      45     90277       3  0.100000          2
12      13   48          23     114     93106       2  3.800000          3
13      14   59          32      40     94920       4  2.500000          2
14      15   67          41     112     91741       1  2.000000          1
15      16   60          30      22     95054       1  1.500000          3
16      17   38          14     130     95010       4  4.700000          3
17      18   42          18      81     94305       4  2.400000          1
18      19   46          21     193     91604       2  8.100000          3
19      20   55          28      21     94720       1  0.500000          2
20      21   56          31      25     94015       4  0.900000          2
21      22   57          27      63     90095       3  2.000000          3
22      23   29           5      62     90277       1  1.200000          1
23      24   44          18      43     91320       2  0.700000          1
24      25   36          11     152     95521       2  3.900000          1
25      26   43          19      29     94305       3  0.500000          1
26      27   40          16      83     95064       4  0.200000          3
27      28   46          20     158     90064       1  2.400000          1
28      29   56          30      48     94539       1  2.200000          3
29      30   38          13     119     94104       1  3.300000          2
...    ...  ...         ...     ...       ...     ...       ...        ...
4970  4971   37          13      95     95821       2  1.700000          2
4971  4972   58          28      73     90024       1  1.400000          3
4972  4973   58          32      41     93401       3  2.200000          3
4973  4974   31           1      68     95045       4  4.000000          3
4974  4975   59          33      64     92867       4  1.700000          2
4975  4976   38          11      29     95207       4  1.000000          2
4976  4977   29           5      31     95039       1  1.800000          2
4977  4978   40          15      54     90266       3  0.800000          3
4978  4979   57          27      63     90210       4  2.000000          3
4979  4980   50          26      92     90740       1  2.600000          2
4980  4981   29           5     135     95762       3  5.300000          1
4981  4982   34           9     195     90266       2  3.000000          1
4982  4983   36          10      45     95126       4  0.200000          1
4983  4984   51          26      72     95370       1  2.900000          1
4984  4985   27           1      98     94043       4  2.300000          3
4985  4986   48          23      30     94720       3  1.700000          2
4986  4987   32           6      78     95825       1  2.900000          3
4987  4988   48          23      43     93943       3  1.700000          2
4988  4989   34           8      85     95134       1  2.500000          1
4989  4990   24           0      38     93555       1  1.000000          3
4990  4991   55          25      58     95023       4  2.000000          3
4991  4992   51          25      92     91330       1  1.900000          2
4992  4993   30           5      13     90037       4  0.500000          3
4993  4994   45          21     218     91801       2  6.666667          1
4994  4995   64          40      75     94588       3  2.000000          3
4995  4996   29           3      40     92697       1  1.900000          3
4996  4997   30           4      15     92037       4  0.400000          1
4997  4998   63          39      24     93023       2  0.300000          3
4998  4999   65          40      49     90034       3  0.500000          2
4999  5000   28           4      83     92612       3  0.800000          1

      Mortgage  Securities Account  CD Account  Online  CreditCard
0            0                   1           0       0           0
1            0                   1           0       0           0
2            0                   0           0       0           0
3            0                   0           0       0           0
4            0                   0           0       0           1
5          155                   0           0       1           0
6            0                   0           0       1           0
7            0                   0           0       0           1
8          104                   0           0       1           0
9            0                   0           0       0           0
10           0                   0           0       0           0
11           0                   0           0       1           0
12           0                   1           0       0           0
13           0                   0           0       1           0
14           0                   1           0       0           0
15           0                   0           0       1           1
16         134                   0           0       0           0
17           0                   0           0       0           0
18           0                   0           0       0           0
19           0                   1           0       0           1
20         111                   0           0       1           0
21           0                   0           0       1           0
22         260                   0           0       1           0
23         163                   1           0       0           0
24         159                   0           0       0           1
25          97                   0           0       1           0
26           0                   0           0       0           0
27           0                   0           0       1           1
28           0                   0           0       1           1
29           0                   0           1       1           1
...        ...                 ...         ...     ...         ...
4970         0                   0           0       0           1
4971         0                   1           0       0           0
4972       148                   0           0       1           1
4973         0                   0           0       1           0
4974         0                   0           0       0           1
4975         0                   0           0       1           0
4976         0                   0           0       1           1
4977         0                   0           0       1           0
4978         0                   0           0       1           0
4979       213                   0           0       0           1
4980         0                   0           1       1           1
4981       122                   0           0       1           0
4982         0                   0           0       0           1
4983         0                   0           0       0           0
4984         0                   0           0       0           1
4985       162                   0           0       1           0
4986         0                   0           0       0           0
4987       159                   0           0       1           0
4988       136                   0           0       0           1
4989         0                   0           0       1           0
4990       219                   0           0       0           1
4991       100                   0           0       0           1
4992         0                   0           0       0           0
4993         0                   0           0       1           0
4994         0                   0           0       1           0
4995         0                   0           0       1           0
4996        85                   0           0       1           0
4997         0                   0           0       0           0
4998         0                   0           0       1           0
4999         0                   0           0       1           1

[5000 rows x 13 columns]
0       0
1       0
2       0
3       0
4       0
5       0
6       0
7       0
8       0
9       1
10      0
11      0
12      0
13      0
14      0
15      0
16      1
17      0
18      1
19      0
20      0
21      0
22      0
23      0
24      0
25      0
26      0
27      0
28      0
29      1
       ..
4970    0
4971    0
4972    0
4973    0
4974    0
4975    0
4976    0
4977    0
4978    0
4979    0
4980    1
4981    0
4982    0
4983    0
4984    0
4985    0
4986    0
4987    0
4988    0
4989    0
4990    0
4991    0
4992    0
4993    0
4994    0
4995    0
4996    0
4997    0
4998    0
4999    0
Name: Personal Loan, Length: 5000, dtype: int64

In [9]:
data.isna().sum()

ID                    0
Age                   0
Experience            0
Income                0
ZIP Code              0
Family                0
CCAvg                 0
Education             0
Mortgage              0
Personal Loan         0
Securities Account    0
CD Account            0
Online                0
CreditCard            0
dtype: int64

In [10]:
x1 = sm.add_constant(x)
result = sm.Logit(y, x1).fit()
result.summary()

C:\Users\gauri\Anaconda3\lib\site-packages\numpy\core\fromnumeric.py:2389: FutureWarning: Method .ptp is deprecated and will be removed in a future version. Use numpy.ptp instead.
  return ptp(axis=axis, out=out, **kwargs)

Optimization terminated successfully.
         Current function value: 0.128331
         Iterations 9

<class 'statsmodels.iolib.summary.Summary'>
"""
                           Logit Regression Results
==============================================================================
Dep. Variable:          Personal Loan   No. Observations:                 5000
Model:                          Logit   Df Residuals:                     4986
Method:                           MLE   Df Model:                           13
Date:                Mon, 22 Mar 2021   Pseudo R-squ.:                  0.5942
Time:                        17:09:43   Log-Likelihood:                -641.65
converged:                       True   LL-Null:                       -1581.0
                                        LLR p-value:                     0.000
======================================================================================
                         coef    std err          z      P>|z|      [0.025      0.975]
--------------------------------------------------------------------------------------
const                -11.7179      4.115     -2.847      0.004     -19.784      -3.652
ID                  -5.23e-05   5.14e-05     -1.017      0.309      -0.000    4.85e-05
Age                   -0.0538      0.061     -0.877      0.380      -0.174       0.066
Experience             0.0639      0.061      1.048      0.295      -0.056       0.183
Income                 0.0547      0.003     20.820      0.000       0.050       0.060
ZIP Code           -3.743e-06   4.07e-05     -0.092      0.927   -8.35e-05    7.61e-05
Family                 0.6952      0.074      9.353      0.000       0.549       0.841
CCAvg                  0.1218      0.040      3.070      0.002       0.044       0.200
Education              1.7404      0.115     15.098      0.000       1.514       1.966
Mortgage               0.0005      0.001      0.836      0.403      -0.001       0.002
Securities Account    -0.9453      0.286     -3.305      0.001      -1.506      -0.385
CD Account             3.8232      0.324     11.791      0.000       3.188       4.459
Online                -0.6717      0.157     -4.272      0.000      -0.980      -0.364
CreditCard            -1.1136      0.205     -5.430      0.000      -1.516      -0.712
======================================================================================
"""

When a bank wants to offer a loan, the following factors are highly significant:

Annual income of the customer
Family size of the customer
Education Level. 1: Undergrad; 2: Graduate; 3: Advanced/Professional
Does the customer have a certificate of deposit (CD) account with the bank?
Does the customer use internet banking facilities?
Does the customer use a credit card issued by UniversalBank?

In [16]:
X = data[['Income', 'Family', 'Education', 'CD Account', 'Online', 'CreditCard']]
Y = data['Personal Loan']
print(X.head())
print(Y.head())

   Income  Family  Education  CD Account  Online  CreditCard
0      49       4          1           0       0           0
1      34       3          1           0       0           0
2      11       1          1           0       0           0
3     100       1          2           0       0           0
4      45       4          2           0       0           1
0    0
1    0
2    0
3    0
4    0
Name: Personal Loan, dtype: int64

In [17]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 2)
print(x_train.shape, x_test.shape, y_train.shape, y_test.shape)

(4000, 13) (1000, 13) (4000,) (1000,)

In [18]:
from sklearn.linear_model import LogisticRegression 
log_reg = LogisticRegression()
log_reg.fit(x_train, y_train)
y_pred = log_reg.predict(x_test)
y_pred

C:\Users\gauri\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)

array([0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 0], dtype=int64)

In [20]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
print(cm)

[[880  29]
 [ 66  25]]

In [22]:
print(log_reg.score(x_test, y_test))

0.905